# Generated by Django 2.0.3 on 2018-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=60, verbose_name='nome_disciplina')),
                ('semestre_ofertado', models.IntegerField(verbose_name='semestre_ofertado')),
                ('ano_ofertado', models.IntegerField(verbose_name='ano_ofertado')),
                ('sequencial', models.IntegerField(verbose_name='sequencial')),
                ('data', models.DateField(verbose_name='data')),
                ('titulo', models.CharField(max_length=60, verbose_name='nome_disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(verbose_name='ra_aluno')),
                ('nome_disciplina', models.CharField(max_length=60, verbose_name='nome_disciplina')),
                ('semestre_ofertado', models.IntegerField(verbose_name='semestre_ofertado')),
                ('ano_ofertado', models.IntegerField(verbose_name='ano_ofertado')),
                ('sequencial_atividade', models.IntegerField(verbose_name='sequencial_atividade')),
                ('nota', models.IntegerField(verbose_name='sequencial')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(verbose_name='ra_aluno')),
                ('nome_disciplina', models.CharField(max_length=60, verbose_name='nome_disciplina')),
                ('ano_ofertado', models.IntegerField(verbose_name='ano_ofertado')),
                ('semestre_ofertado', models.IntegerField(verbose_name='semestre_ofertado')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(verbose_name='ra_aluno')),
                ('senha', models.CharField(max_length=20, verbose_name='senha')),
            ],
        ),
    ]
